'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert('company', [
      {
        type: 1,
        company_name: 'Hester-Hamilton',
        company_email: 'willie14@example.org',
        company_phone_number: 932768053813,
        tax_code: '6491949162',
        size: 2,
        company_location: '206 Donna Cove, Port Rachel, South Dakota 86068, Guinea',
        company_description: 'Re-contextualized even-keeled ability',
        company_website_url: 'https://www.ward.net/',
      },
      {
        type: 2,
        company_name: 'Ramirez PLC',
        company_email: 'steveallen@example.org',
        company_phone_number: 927622213781,
        tax_code: '7100895209',
        size: 3,
        company_location: '156 Erin Harbors, Lake Christopher, Nebraska 94725, Lithuania',
        company_description: 'De-engineered hybrid migration',
        company_website_url: 'http://wheeler-gonzalez.net/',
      },
      {
        type: 2,
        company_name: 'Porter and Sons',
        company_email: 'tanyamcdonald@example.net',
        company_phone_number: 396120529637,
        tax_code: '8602980545',
        size: 2,
        company_location: '21024 Rachel Common, Bushtown, New Mexico 74384, Dominican Republic',
        company_description: 'Multi-layered analyzing data-warehouse',
        company_website_url: 'http://www.mcdonald.biz/',
      },
      {
        type: 2,
        company_name: 'Jennings LLC',
        company_email: 'pglover@example.org',
        company_phone_number: 81796570794,
        tax_code: '8522581499',
        size: 5,
        company_location: '7561 Tammy Alley, Port Matthew, Mississippi 82416, Tuvalu',
        company_description: 'Synergistic real-time software',
        company_website_url: 'http://boyle.info/',
      },
      {
        type: 1,
        company_name: 'Nguyen, Chen and Olson',
        company_email: 'elizabethking@example.net',
        company_phone_number: 113922258081,
        tax_code: '9421362305',
        size: 2,
        company_location: '056 David Rest, New Edgarburgh, Georgia 80234, Niger',
        company_description: 'Sharable upward-trending solution',
        company_website_url: 'https://www.bryant-white.biz/',
      },
      {
        type: 1,
        company_name: 'Lawrence, Le and Oconnell',
        company_email: 'nmann@example.net',
        company_phone_number: 669911560003,
        tax_code: '5202818215',
        size: 3,
        company_location: '49013 Bartlett Mountain, West Lindaton, California 14099, Egypt',
        company_description: 'Adaptive 4thgeneration service-desk',
        company_website_url: 'https://gay-lawson.com/',
      },
      {
        type: 2,
        company_name: 'Lawson PLC',
        company_email: 'leejordan@example.com',
        company_phone_number: 874132807230,
        tax_code: '3340399610',
        size: 1,
        company_location: '89232 Jennifer Point, Rogersbury, Nebraska 91086, Guernsey',
        company_description: 'Open-source asynchronous productivity',
        company_website_url: 'https://www.lopez-patel.info/',
      },
      {
        type: 2,
        company_name: 'Murray, Moss and Smith',
        company_email: 'kweber@example.com',
        company_phone_number: 212725791796,
        tax_code: '3749636200',
        size: 1,
        company_location: '9254 Myers Parkway, New Jennifer, Montana 23639, Palestinian Territory',
        company_description: 'Multi-channeled user-facing standardization',
        company_website_url: 'https://santiago-adkins.com/',
      },
      {
        type: 2,
        company_name: 'Mann-Edwards',
        company_email: 'karenhawkins@example.net',
        company_phone_number: 654439380941,
        tax_code: '2821341989',
        size: 5,
        company_location: '42428 Joel Neck, New Carlhaven, New Jersey 14561, Tanzania',
        company_description: 'Fundamental 3rdgeneration adapter',
        company_website_url: 'http://www.powell.net/',
      },
      {
        type: 2,
        company_name: 'Reynolds, Wolfe and Castaneda',
        company_email: 'brownian@example.org',
        company_phone_number: 625219837414,
        tax_code: '7195175505',
        size: 2,
        company_location: '79367 Jesse Trafficway, New Angela, Iowa 68473, Iceland',
        company_description: 'Re-contextualized multi-tasking Internet solution',
        company_website_url: 'https://rodriguez.info/',
      },
      {
        type: 1,
        company_name: 'Finley, Tucker and Roberson',
        company_email: 'holly66@example.net',
        company_phone_number: 51702058119,
        tax_code: '5326943512',
        size: 1,
        company_location: '072 Mcclain Island, Lewisview, Maine 50696, New Caledonia',
        company_description: 'De-engineered context-sensitive hub',
        company_website_url: 'https://miller.biz/',
      },
      {
        type: 2,
        company_name: 'Thompson Ltd',
        company_email: 'miguelweber@example.org',
        company_phone_number: 790249115299,
        tax_code: '3710940550',
        size: 5,
        company_location: '1864 Lynch Mountain, Joshuaton, Arkansas 79209, Hong Kong',
        company_description: 'Function-based 3rdgeneration alliance',
        company_website_url: 'https://crawford-sanchez.com/',
      },
      {
        type: 2,
        company_name: 'Smith-Green',
        company_email: 'cgeorge@example.net',
        company_phone_number: 159850668335,
        tax_code: '3285933172',
        size: 2,
        company_location:
          '723 Sarah Skyway, East Amber, Delaware 23652, Antarctica (the territory South of 60 deg S)',
        company_description: 'Synchronized global circuit',
        company_website_url: 'http://www.reese-diaz.com/',
      },
      {
        type: 2,
        company_name: 'Davis, Todd and Williams',
        company_email: 'cindy58@example.net',
        company_phone_number: 572670292308,
        tax_code: '2238822188',
        size: 2,
        company_location: '06902 Kevin Island, Rickberg, Vermont 34651, Turkey',
        company_description: 'Expanded client-driven toolset',
        company_website_url: 'https://www.johnson.com/',
      },
      {
        type: 2,
        company_name: 'Ramirez-Cantrell',
        company_email: 'joseph43@example.org',
        company_phone_number: 759001647162,
        tax_code: '4609616465',
        size: 2,
        company_location: '7559 Brittany Avenue, West Tracy, Montana 26245, Syrian Arab Republic',
        company_description: 'Public-key real-time analyzer',
        company_website_url: 'http://www.smith-thornton.com/',
      },
      {
        type: 2,
        company_name: 'Moses, Thompson and Guzman',
        company_email: 'hughesryan@example.com',
        company_phone_number: 766608870884,
        tax_code: '0486482449',
        size: 1,
        company_location: '08414 Margaret Estate, North Drewbury, Illinois 00746, United Kingdom',
        company_description: 'User-friendly multi-tasking solution',
        company_website_url: 'https://www.sullivan.com/',
      },
      {
        type: 1,
        company_name: 'Horn, Hernandez and Cunningham',
        company_email: 'wnguyen@example.com',
        company_phone_number: 358265322299,
        tax_code: '1615621083',
        size: 5,
        company_location: '66589 Jason Village, East Shawn, Ohio 58603, Congo',
        company_description: 'Centralized discrete access',
        company_website_url: 'https://www.spencer.com/',
      },
      {
        type: 2,
        company_name: 'Peterson, Armstrong and Combs',
        company_email: 'nielsenaustin@example.com',
        company_phone_number: 719596998065,
        tax_code: '7995524846',
        size: 5,
        company_location: '30226 Nicole Inlet, Guzmanview, New Jersey 82714, Italy',
        company_description: 'Optional dynamic application',
        company_website_url: 'https://warren.com/',
      },
      {
        type: 1,
        company_name: 'Munoz and Sons',
        company_email: 'sandramoore@example.net',
        company_phone_number: 233300179427,
        tax_code: '8826432821',
        size: 3,
        company_location: '3757 Rebecca Passage, Brayland, Oklahoma 78968, Oman',
        company_description: 'Right-sized stable forecast',
        company_website_url: 'http://hernandez-webb.net/',
      },
      {
        type: 2,
        company_name: 'Cobb, Ballard and Evans',
        company_email: 'davisregina@example.com',
        company_phone_number: 696708088715,
        tax_code: '5409554552',
        size: 4,
        company_location: '87209 Palmer Dam, Christineland, Vermont 75180, Azerbaijan',
        company_description: 'Expanded non-volatile groupware',
        company_website_url: 'http://clark-gamble.biz/',
      },
      {
        type: 2,
        company_name: 'Blackwell Ltd',
        company_email: 'knichols@example.net',
        company_phone_number: 900774760366,
        tax_code: '9896860528',
        size: 1,
        company_location:
          '557 Jason Common, South Curtis, Massachusetts 63296, Bouvet Island (Bouvetoya)',
        company_description: 'Quality-focused coherent definition',
        company_website_url: 'http://www.wang.com/',
      },
      {
        type: 1,
        company_name: 'Watkins and Sons',
        company_email: 'michael52@example.net',
        company_phone_number: 795031776300,
        tax_code: '4752726459',
        size: 2,
        company_location:
          '96678 Johnson Plaza, West Lisamouth, Oklahoma 39157, British Virgin Islands',
        company_description: 'Expanded 3rdgeneration instruction set',
        company_website_url: 'https://www.pearson-byrd.info/',
      },
      {
        type: 2,
        company_name: 'Lloyd Inc',
        company_email: 'lclarke@example.net',
        company_phone_number: 547030310727,
        tax_code: '8386503944',
        size: 1,
        company_location: '3353 Carol Fort, North Jamestown, Wisconsin 80409, Czech Republic',
        company_description: 'Ergonomic stable leverage',
        company_website_url: 'http://thompson.com/',
      },
      {
        type: 1,
        company_name: 'Mendoza-Brown',
        company_email: 'richardsondenise@example.com',
        company_phone_number: 952816907864,
        tax_code: '6581526016',
        size: 2,
        company_location: '958 William Canyon, Michaelside, New Jersey 46913, Morocco',
        company_description: 'Integrated neutral firmware',
        company_website_url: 'https://www.martin-johnson.biz/',
      },
      {
        type: 1,
        company_name: 'Johnson, Rodriguez and Waters',
        company_email: 'smiranda@example.org',
        company_phone_number: 447436503717,
        tax_code: '1628561216',
        size: 1,
        company_location: '077 Julie Creek, Markborough, Maine 85144, Saint Martin',
        company_description: 'Multi-lateral transitional data-warehouse',
        company_website_url: 'https://schroeder.com/',
      },
      {
        type: 2,
        company_name: 'Gill and Sons',
        company_email: 'arroyochristopher@example.net',
        company_phone_number: 76900091744,
        tax_code: '4656805652',
        size: 1,
        company_location: '785 Thomas Junction, Kaylatown, Texas 64257, Mauritania',
        company_description: 'Configurable explicit superstructure',
        company_website_url: 'http://www.perez.com/',
      },
      {
        type: 2,
        company_name: 'Figueroa, Davis and Vaughn',
        company_email: 'pstevens@example.com',
        company_phone_number: 673929974275,
        tax_code: '3706509651',
        size: 3,
        company_location: '0359 Smith Roads, North Laurahaven, Alabama 67865, Tajikistan',
        company_description: 'Up-sized system-worthy hub',
        company_website_url: 'https://www.bailey.org/',
      },
      {
        type: 2,
        company_name: 'Perkins, Walters and Randall',
        company_email: 'thomasshawn@example.org',
        company_phone_number: 710991936276,
        tax_code: '8759682275',
        size: 1,
        company_location: '140 Vang Mills, Stephentown, North Carolina 91682, Paraguay',
        company_description: 'Adaptive even-keeled frame',
        company_website_url: 'http://www.davis-mayo.net/',
      },
      {
        type: 1,
        company_name: 'Jones, Melendez and Bray',
        company_email: 'christopherlee@example.net',
        company_phone_number: 844806187256,
        tax_code: '2550787942',
        size: 5,
        company_location: '0550 Thomas Underpass, West Edwardfort, Minnesota 94288, Chad',
        company_description: 'Adaptive systemic installation',
        company_website_url: 'http://norris-callahan.com/',
      },
      {
        type: 1,
        company_name: 'Hughes, Oliver and Wilson',
        company_email: 'jacobwall@example.net',
        company_phone_number: 719049435831,
        tax_code: '6618045603',
        size: 5,
        company_location: '97850 Miranda Expressway, North Laura, Georgia 48748, Philippines',
        company_description: 'Grass-roots coherent process improvement',
        company_website_url: 'https://spencer.biz/',
      },
      {
        type: 2,
        company_name: 'Gallegos Inc',
        company_email: 'joshua18@example.org',
        company_phone_number: 980873618289,
        tax_code: '0359492037',
        size: 3,
        company_location:
          '96305 Jordan Plains, Port Emilyburgh, Washington 47283, British Virgin Islands',
        company_description: 'Streamlined secondary intranet',
        company_website_url: 'https://anderson-roberts.org/',
      },
      {
        type: 2,
        company_name: 'Padilla-Taylor',
        company_email: 'frances97@example.net',
        company_phone_number: 384928728238,
        tax_code: '8090109112',
        size: 5,
        company_location: '83459 Jones Shoal, Murphyburgh, Connecticut 43422, Norway',
        company_description: 'Assimilated executive initiative',
        company_website_url: 'https://horn-crane.com/',
      },
      {
        type: 1,
        company_name: 'Johnson-Silva',
        company_email: 'vsuarez@example.net',
        company_phone_number: 825677450342,
        tax_code: '1580190395',
        size: 2,
        company_location: '934 Andrew Parkways, Craigborough, Wyoming 30818, Bangladesh',
        company_description: 'Reduced multimedia neural-net',
        company_website_url: 'http://ortiz.org/',
      },
      {
        type: 2,
        company_name: 'Rivera, Rogers and Wallace',
        company_email: 'rushbonnie@example.net',
        company_phone_number: 103100435202,
        tax_code: '2679348058',
        size: 1,
        company_location:
          '778 Patrick Forge, Ortegachester, New York 75334, British Virgin Islands',
        company_description: 'Object-based attitude-oriented leverage',
        company_website_url: 'http://www.sandoval.com/',
      },
      {
        type: 2,
        company_name: 'Hunter, Wright and Walsh',
        company_email: 'yroy@example.com',
        company_phone_number: 973213676886,
        tax_code: '6004043293',
        size: 3,
        company_location: '65653 Zachary Way, Lake Hollyside, Alaska 65210, Denmark',
        company_description: 'Enhanced motivating alliance',
        company_website_url: 'https://king-jones.info/',
      },
      {
        type: 1,
        company_name: 'Williams, Hansen and Hayden',
        company_email: 'heather75@example.com',
        company_phone_number: 392318929507,
        tax_code: '8377385773',
        size: 4,
        company_location: '3930 Parker Port, New Wayne, Utah 34284, Guyana',
        company_description: 'Reverse-engineered fresh-thinking infrastructure',
        company_website_url: 'http://harrison.com/',
      },
      {
        type: 1,
        company_name: 'Morales PLC',
        company_email: 'gonzalesapril@example.com',
        company_phone_number: 242812483816,
        tax_code: '0185688531',
        size: 5,
        company_location: '61399 Nicole Trace, Port Sarahside, Maryland 00839, Sudan',
        company_description: 'Stand-alone attitude-oriented portal',
        company_website_url: 'https://kirby.info/',
      },
      {
        type: 2,
        company_name: 'Bell, Brooks and Mckay',
        company_email: 'jonesteresa@example.net',
        company_phone_number: 100171890962,
        tax_code: '2998064892',
        size: 1,
        company_location: '066 Morgan Springs, Snyderfort, Pennsylvania 91514, Zambia',
        company_description: 'Monitored systematic installation',
        company_website_url: 'http://www.barnes.com/',
      },
      {
        type: 1,
        company_name: 'Garza-Kent',
        company_email: 'kennethburgess@example.net',
        company_phone_number: 611426239019,
        tax_code: '9109027674',
        size: 4,
        company_location: '0950 Raymond Ramp, Port Raymondport, Minnesota 14754, Cambodia',
        company_description: 'Down-sized dedicated project',
        company_website_url: 'http://howard.com/',
      },
      {
        type: 2,
        company_name: 'Rangel and Sons',
        company_email: 'wallsann@example.net',
        company_phone_number: 541733180575,
        tax_code: '0401887187',
        size: 5,
        company_location: '970 William Brook, Wesleyborough, Alabama 54117, Nepal',
        company_description: 'Right-sized grid-enabled challenge',
        company_website_url: 'https://www.cox.com/',
      },
      {
        type: 1,
        company_name: 'Baker, Moody and Hardin',
        company_email: 'michaeldoyle@example.org',
        company_phone_number: 188202364845,
        tax_code: '8528350177',
        size: 2,
        company_location: '72958 Anderson Locks, Andrewchester, Colorado 02098, Ghana',
        company_description: 'Innovative directional hub',
        company_website_url: 'https://porter.biz/',
      },
      {
        type: 1,
        company_name: 'Brown-Barber',
        company_email: 'kcase@example.net',
        company_phone_number: 400984872407,
        tax_code: '9795921152',
        size: 1,
        company_location: '92298 Torres Drive, Maryside, North Dakota 58755, Montserrat',
        company_description: 'Decentralized incremental workforce',
        company_website_url: 'http://www.mendoza.biz/',
      },
      {
        type: 1,
        company_name: 'Rodriguez-Zavala',
        company_email: 'justinroth@example.net',
        company_phone_number: 855342173459,
        tax_code: '1612540439',
        size: 3,
        company_location: '2506 John Radial, South Christine, Connecticut 67303, Estonia',
        company_description: 'Future-proofed executive contingency',
        company_website_url: 'http://www.acevedo.biz/',
      },
      {
        type: 2,
        company_name: 'Buck, Pena and Green',
        company_email: 'natalieduncan@example.net',
        company_phone_number: 643637466712,
        tax_code: '2763271905',
        size: 3,
        company_location: '3115 Jeremy Prairie, Besthaven, Oregon 99543, Cocos (Keeling) Islands',
        company_description: 'Public-key well-modulated knowledge user',
        company_website_url: 'http://scott.biz/',
      },
      {
        type: 1,
        company_name: 'Koch LLC',
        company_email: 'reneecarroll@example.org',
        company_phone_number: 393888754131,
        tax_code: '7631398859',
        size: 5,
        company_location: '2203 Rivera Viaduct, South Sharon, Pennsylvania 82335, Argentina',
        company_description: 'Exclusive client-server emulation',
        company_website_url: 'https://thomas-wilkinson.net/',
      },
      {
        type: 1,
        company_name: 'Knox-Martin',
        company_email: 'angela66@example.net',
        company_phone_number: 407398566355,
        tax_code: '3722040934',
        size: 2,
        company_location: '151 Perez Trail, Charlestown, Louisiana 71173, Puerto Rico',
        company_description: 'Pre-emptive tangible knowledge user',
        company_website_url: 'https://www.howe-lopez.info/',
      },
      {
        type: 1,
        company_name: 'Ruiz, Donaldson and Nielsen',
        company_email: 'dbaker@example.org',
        company_phone_number: 591311106070,
        tax_code: '8571194070',
        size: 4,
        company_location: '41974 Poole Neck, Petersentown, Nevada 37419, Mongolia',
        company_description: 'Secured scalable contingency',
        company_website_url: 'https://mcguire.com/',
      },
      {
        type: 2,
        company_name: 'Smith-Sanchez',
        company_email: 'shellypeck@example.org',
        company_phone_number: 590492163250,
        tax_code: '2874162384',
        size: 5,
        company_location: '25885 Brian Mews, Franciscofurt, Nevada 24793, Armenia',
        company_description: 'Synergistic local customer loyalty',
        company_website_url: 'http://harvey-kelley.com/',
      },
      {
        type: 2,
        company_name: 'Farrell-Thomas',
        company_email: 'aarontorres@example.org',
        company_phone_number: 987967325277,
        tax_code: '7992045790',
        size: 3,
        company_location: '10301 Daniel Locks, Mcmahonfort, Arizona 87893, Serbia',
        company_description: 'Intuitive neutral migration',
        company_website_url: 'https://wright.biz/',
      },
      {
        type: 2,
        company_name: 'Simon Group',
        company_email: 'ryandavis@example.com',
        company_phone_number: 582030242414,
        tax_code: '3406070750',
        size: 2,
        company_location: '7390 Alexander Grove, New Jasmineview, West Virginia 34695, Venezuela',
        company_description: 'Down-sized client-server approach',
        company_website_url: 'https://gonzalez-phillips.com/',
      },
      {
        type: 1,
        company_name: 'Velez and Sons',
        company_email: 'blakejeremy@example.net',
        company_phone_number: 223529150512,
        tax_code: '7221278847',
        size: 2,
        company_location: '758 Thompson Grove, Lake Jessestad, Rhode Island 87471, Seychelles',
        company_description: 'Down-sized demand-driven alliance',
        company_website_url: 'http://malone.com/',
      },
      {
        type: 2,
        company_name: 'Stewart-Silva',
        company_email: 'faithburke@example.net',
        company_phone_number: 357330598062,
        tax_code: '5796805962',
        size: 3,
        company_location: '14263 White Mountain, North Matthewside, Alabama 82205, North Macedonia',
        company_description: 'Reduced bottom-line archive',
        company_website_url: 'https://cook-rivera.com/',
      },
      {
        type: 1,
        company_name: 'Conrad, Jacobs and Owen',
        company_email: 'michael12@example.org',
        company_phone_number: 403681051508,
        tax_code: '8692484977',
        size: 2,
        company_location: '5862 Collins Ferry, New Rachelton, Massachusetts 35595, Philippines',
        company_description: 'Enterprise-wide high-level interface',
        company_website_url: 'https://www.jones-brown.biz/',
      },
      {
        type: 2,
        company_name: 'Thompson-Lyons',
        company_email: 'kristascott@example.com',
        company_phone_number: 664706480134,
        tax_code: '4096168930',
        size: 1,
        company_location: '8853 Jacob Station, Bettyshire, Alabama 14062, Nigeria',
        company_description: 'Ameliorated bifurcated function',
        company_website_url: 'https://www.hall.net/',
      },
      {
        type: 1,
        company_name: 'Daugherty-Jones',
        company_email: 'jasonrodriguez@example.com',
        company_phone_number: 806500142503,
        tax_code: '9689310770',
        size: 3,
        company_location: '44584 Graham Route, East Charles, Oregon 15635, Marshall Islands',
        company_description: 'User-friendly intangible benchmark',
        company_website_url: 'https://www.romero.info/',
      },
      {
        type: 1,
        company_name: 'Wood-Carter',
        company_email: 'jennifer23@example.net',
        company_phone_number: 66247669885,
        tax_code: '0010054367',
        size: 1,
        company_location: '7096 Stuart Estates, Johnhaven, Maine 35363, Austria',
        company_description: 'Synchronized bottom-line neural-net',
        company_website_url: 'https://www.dixon-williams.biz/',
      },
      {
        type: 2,
        company_name: 'Hernandez and Sons',
        company_email: 'fmelton@example.org',
        company_phone_number: 401603437435,
        tax_code: '3407741725',
        size: 5,
        company_location: '73542 Lee Square, East Derrickview, Arkansas 61299, Finland',
        company_description: 'Fundamental intangible orchestration',
        company_website_url: 'http://www.davis.com/',
      },
      {
        type: 2,
        company_name: 'Williams PLC',
        company_email: 'rickystewart@example.com',
        company_phone_number: 894879695971,
        tax_code: '0426950139',
        size: 4,
        company_location: '217 Jeffrey Camp, West Dawn, Michigan 45030, Belarus',
        company_description: 'Reduced secondary matrices',
        company_website_url: 'http://www.hendrix.biz/',
      },
      {
        type: 2,
        company_name: 'Sweeney, Mason and Allen',
        company_email: 'castillomary@example.net',
        company_phone_number: 339266717306,
        tax_code: '5321459762',
        size: 3,
        company_location: '89080 Eric Union, New Jenniferhaven, Missouri 27587, Spain',
        company_description: 'Front-line mobile encoding',
        company_website_url: 'http://morrison.biz/',
      },
      {
        type: 1,
        company_name: 'Hunt-Cole',
        company_email: 'vchen@example.org',
        company_phone_number: 876892863597,
        tax_code: '9408521132',
        size: 2,
        company_location: '467 Wise Ramp, Thomasstad, Nebraska 59967, Kuwait',
        company_description: 'Operative methodical collaboration',
        company_website_url: 'http://beck-schneider.com/',
      },
      {
        type: 2,
        company_name: 'Evans-Wallace',
        company_email: 'jeffreyvincent@example.net',
        company_phone_number: 158040650889,
        tax_code: '4885388538',
        size: 1,
        company_location:
          '26011 Stephen Rapids, West Jasonshire, Virginia 20359, Trinidad and Tobago',
        company_description: 'Pre-emptive even-keeled neural-net',
        company_website_url: 'http://koch.org/',
      },
      {
        type: 2,
        company_name: 'Reed, Smith and Barton',
        company_email: 'bennettdavid@example.com',
        company_phone_number: 635410496079,
        tax_code: '0830628397',
        size: 4,
        company_location: '83247 Natalie Forest, Lake Pamela, Nebraska 04957, Tanzania',
        company_description: 'Enterprise-wide needs-based Graphic Interface',
        company_website_url: 'https://www.chang.net/',
      },
      {
        type: 1,
        company_name: 'Zavala-Long',
        company_email: 'nathanwood@example.org',
        company_phone_number: 289869163293,
        tax_code: '8642046065',
        size: 4,
        company_location: '105 Hernandez Loaf, South Anthony, South Carolina 24618, Montenegro',
        company_description: 'Quality-focused 6thgeneration firmware',
        company_website_url: 'http://anderson.com/',
      },
      {
        type: 2,
        company_name: 'Ibarra PLC',
        company_email: 'melissahernandez@example.net',
        company_phone_number: 544144007330,
        tax_code: '5139719021',
        size: 5,
        company_location: '3411 Grant Isle, Port Anthonychester, Washington 19058, Australia',
        company_description: 'Multi-lateral tangible forecast',
        company_website_url: 'http://shelton.biz/',
      },
      {
        type: 2,
        company_name: 'Walker-Lee',
        company_email: 'christophercruz@example.net',
        company_phone_number: 425084961688,
        tax_code: '0382512762',
        size: 5,
        company_location: '918 Koch Keys, Chelseashire, Washington 94431, Cameroon',
        company_description: 'Programmable eco-centric instruction set',
        company_website_url: 'https://brown.net/',
      },
      {
        type: 2,
        company_name: 'Bell and Sons',
        company_email: 'michael27@example.net',
        company_phone_number: 741532807525,
        tax_code: '8092976286',
        size: 3,
        company_location: '5129 Garza Grove, East Mary, Minnesota 47972, Namibia',
        company_description: 'Implemented bandwidth-monitored architecture',
        company_website_url: 'https://www.smith.com/',
      },
      {
        type: 1,
        company_name: 'Curry Ltd',
        company_email: 'mooremichael@example.org',
        company_phone_number: 402905387283,
        tax_code: '4972722900',
        size: 1,
        company_location: '0730 Ewing Causeway, Port James, Hawaii 22064, Japan',
        company_description: 'Cloned object-oriented approach',
        company_website_url: 'https://garrett.com/',
      },
      {
        type: 2,
        company_name: 'Barnett, Fox and Michael',
        company_email: 'bonniemullins@example.net',
        company_phone_number: 977225670218,
        tax_code: '3242298391',
        size: 5,
        company_location: '25998 Fletcher Knoll, East Tonya, Vermont 33344, India',
        company_description: 'Down-sized full-range workforce',
        company_website_url: 'http://cohen-moore.com/',
      },
      {
        type: 1,
        company_name: 'Williams, Swanson and Lee',
        company_email: 'qtaylor@example.org',
        company_phone_number: 943263915447,
        tax_code: '6395496350',
        size: 5,
        company_location: '90745 Tiffany Cove, Meredithview, Michigan 85065, Aruba',
        company_description: 'Mandatory optimizing framework',
        company_website_url: 'http://www.frank-cole.com/',
      },
      {
        type: 2,
        company_name: 'Rogers, Sawyer and Smith',
        company_email: 'petersonjoseph@example.org',
        company_phone_number: 926246674043,
        tax_code: '4451417132',
        size: 5,
        company_location:
          '009 Cortez Isle, Kylehaven, New Hampshire 49859, British Indian Ocean Territory (Chagos Archipelago)',
        company_description: 'Reverse-engineered coherent superstructure',
        company_website_url: 'http://raymond-padilla.info/',
      },
      {
        type: 1,
        company_name: 'Salazar, Parker and Rodriguez',
        company_email: 'michellerichardson@example.com',
        company_phone_number: 235365680619,
        tax_code: '2208277160',
        size: 5,
        company_location: '026 Mendoza Village, Masonview, Louisiana 03579, Armenia',
        company_description: 'Triple-buffered systemic superstructure',
        company_website_url: 'https://reed-vaughn.com/',
      },
      {
        type: 1,
        company_name: 'Weber-Lewis',
        company_email: 'erinnoble@example.org',
        company_phone_number: 568367359969,
        tax_code: '0864552064',
        size: 3,
        company_location: '977 Walker Prairie, North Melissaburgh, Maine 71332, Ecuador',
        company_description: 'Focused systemic hierarchy',
        company_website_url: 'http://cole.com/',
      },
      {
        type: 2,
        company_name: 'Cruz, Smith and Griffin',
        company_email: 'rodriguezkathleen@example.net',
        company_phone_number: 50527750619,
        tax_code: '1462697070',
        size: 3,
        company_location: '0481 Castillo Points, Port Shannon, Oklahoma 52249, Madagascar',
        company_description: 'Function-based cohesive project',
        company_website_url: 'https://adams.com/',
      },
      {
        type: 1,
        company_name: 'Robinson-Salazar',
        company_email: 'obrienthomas@example.org',
        company_phone_number: 521978906592,
        tax_code: '2781135515',
        size: 2,
        company_location:
          '85552 Megan Branch, Lake Evelyntown, Georgia 03086, Syrian Arab Republic',
        company_description: 'Extended upward-trending focus group',
        company_website_url: 'https://lucero.com/',
      },
      {
        type: 2,
        company_name: 'Huber, Cruz and Chandler',
        company_email: 'parksalicia@example.net',
        company_phone_number: 279983063003,
        tax_code: '6575047603',
        size: 3,
        company_location: '679 Williams Drive, North Stephenview, Arizona 61657, Slovenia',
        company_description: 'Up-sized uniform process improvement',
        company_website_url: 'https://smith.info/',
      },
      {
        type: 2,
        company_name: 'Walter Group',
        company_email: 'brooke53@example.com',
        company_phone_number: 25317731054,
        tax_code: '5495961490',
        size: 5,
        company_location: '59880 Sandra Parks, Elliottport, North Dakota 69586, Austria',
        company_description: 'Multi-channeled responsive hub',
        company_website_url: 'https://wells.com/',
      },
      {
        type: 1,
        company_name: 'Mullins-Gonzalez',
        company_email: 'nicholas24@example.com',
        company_phone_number: 920437573442,
        tax_code: '3074769566',
        size: 5,
        company_location:
          '42681 Livingston Summit, Daltonmouth, Maine 71710, Sao Tome and Principe',
        company_description: 'Reactive logistical support',
        company_website_url: 'http://www.mccormick.com/',
      },
      {
        type: 1,
        company_name: 'Combs-Allen',
        company_email: 'joshua62@example.net',
        company_phone_number: 261271977162,
        tax_code: '6066249553',
        size: 2,
        company_location:
          '2110 Lisa Circle, North Andrewshire, Ohio 92181, Svalbard & Jan Mayen Islands',
        company_description: 'Robust needs-based superstructure',
        company_website_url: 'http://www.bell.org/',
      },
      {
        type: 2,
        company_name: 'Foster, Wilson and Nelson',
        company_email: 'rmartinez@example.org',
        company_phone_number: 634773527987,
        tax_code: '2259157974',
        size: 5,
        company_location: '914 Taylor Estate, Stephanieburgh, Rhode Island 31634, Martinique',
        company_description: 'Ameliorated systematic Graphical User Interface',
        company_website_url: 'http://www.farmer-johnson.com/',
      },
      {
        type: 1,
        company_name: 'Perez, Leon and Boyd',
        company_email: 'josephbrennan@example.org',
        company_phone_number: 524759634675,
        tax_code: '6255239035',
        size: 5,
        company_location: '815 Christina Trace, Gibbston, Wisconsin 79525, North Macedonia',
        company_description: 'Ameliorated regional throughput',
        company_website_url: 'https://www.hayes.com/',
      },
      {
        type: 1,
        company_name: 'Taylor-Ross',
        company_email: 'robingonzalez@example.net',
        company_phone_number: 259316304953,
        tax_code: '0640639914',
        size: 1,
        company_location:
          '8602 Montgomery Route, New Terrifurt, South Carolina 06199, British Indian Ocean Territory (Chagos Archipelago)',
        company_description: 'Right-sized high-level budgetary management',
        company_website_url: 'https://www.miller.org/',
      },
      {
        type: 2,
        company_name: 'Rodriguez-Wright',
        company_email: 'johnwiley@example.org',
        company_phone_number: 753284239424,
        tax_code: '2866957592',
        size: 2,
        company_location: '911 Brown Haven, Lake Antonio, Montana 91835, Iceland',
        company_description: 'Centralized background archive',
        company_website_url: 'http://www.miller.com/',
      },
      {
        type: 2,
        company_name: 'Taylor PLC',
        company_email: 'jennifermcdonald@example.net',
        company_phone_number: 86001598071,
        tax_code: '0510322212',
        size: 3,
        company_location:
          '9543 Hicks Shoal, Wayneshire, North Carolina 34265, Falkland Islands (Malvinas)',
        company_description: 'Fully-configurable uniform focus group',
        company_website_url: 'https://henson.info/',
      },
      {
        type: 1,
        company_name: 'Allen-Calhoun',
        company_email: 'sanchezbrian@example.org',
        company_phone_number: 65400188650,
        tax_code: '0109393823',
        size: 1,
        company_location: '577 Ortega Fields, Lake Jacquelinemouth, California 25161, Turkmenistan',
        company_description: 'Persistent multi-state complexity',
        company_website_url: 'http://choi-mitchell.com/',
      },
      {
        type: 1,
        company_name: 'Lowe, Fritz and Miller',
        company_email: 'ashley00@example.org',
        company_phone_number: 75951997783,
        tax_code: '2531901281',
        size: 2,
        company_location:
          '341 Bright Alley, Brianstad, North Carolina 94794, South Georgia and the South Sandwich Islands',
        company_description: 'Object-based solution-oriented strategy',
        company_website_url: 'https://baker-stafford.org/',
      },
      {
        type: 1,
        company_name: 'Martin, Rollins and Figueroa',
        company_email: 'mendeztodd@example.net',
        company_phone_number: 910367794532,
        tax_code: '4217450562',
        size: 4,
        company_location: '122 Jason Inlet, Valentineport, Idaho 09131, Bangladesh',
        company_description: 'Stand-alone coherent interface',
        company_website_url: 'http://sanchez.org/',
      },
      {
        type: 1,
        company_name: 'Reynolds-Hines',
        company_email: 'melissawoods@example.com',
        company_phone_number: 6772366969,
        tax_code: '0594100098',
        size: 5,
        company_location: '0093 Mark Manor, Alexandermouth, Georgia 26015, Cayman Islands',
        company_description: 'Managed 3rdgeneration encryption',
        company_website_url: 'https://holland.com/',
      },
      {
        type: 2,
        company_name: 'Wood, Smith and Morrison',
        company_email: 'victoriagonzalez@example.net',
        company_phone_number: 682788916854,
        tax_code: '1650829964',
        size: 2,
        company_location: '8426 Jamie Alley, North Shannonshire, Wyoming 40984, Micronesia',
        company_description: 'Fully-configurable 24hour hub',
        company_website_url: 'http://clements-ritter.com/',
      },
      {
        type: 2,
        company_name: 'Santana, Daniels and Franklin',
        company_email: 'caitlinlambert@example.org',
        company_phone_number: 198289978455,
        tax_code: '2328496009',
        size: 1,
        company_location: '3097 Brown Corners, Stephaniehaven, Vermont 98268, Japan',
        company_description: 'Multi-layered composite benchmark',
        company_website_url: 'https://www.madden.com/',
      },
      {
        type: 1,
        company_name: 'Sanders, Owens and Johnson',
        company_email: 'peterslaura@example.net',
        company_phone_number: 672339627136,
        tax_code: '3815174359',
        size: 4,
        company_location: '2050 Perez Lakes, Lynnton, Maine 82794, Colombia',
        company_description: 'Triple-buffered incremental projection',
        company_website_url: 'http://rodgers.info/',
      },
      {
        type: 1,
        company_name: 'Sellers-May',
        company_email: 'samantha93@example.org',
        company_phone_number: 29912662093,
        tax_code: '3074148894',
        size: 2,
        company_location: '95231 Heather Trail, Michaelstad, New Jersey 45002, Cayman Islands',
        company_description: 'Mandatory composite orchestration',
        company_website_url: 'https://carey.com/',
      },
      {
        type: 2,
        company_name: 'Fowler, Miller and Fisher',
        company_email: 'allen67@example.org',
        company_phone_number: 490478571185,
        tax_code: '6566974591',
        size: 2,
        company_location: '642 Daniel Fort, West Josephmouth, Wisconsin 30637, Bhutan',
        company_description: 'Horizontal contextually-based parallelism',
        company_website_url: 'https://johnson-vincent.com/',
      },
      {
        type: 2,
        company_name: 'Murphy-Smith',
        company_email: 'qcox@example.org',
        company_phone_number: 720896274528,
        tax_code: '7179212163',
        size: 4,
        company_location: '49203 Ryan Rue, Ginatown, Utah 40820, Netherlands',
        company_description: 'Visionary systematic project',
        company_website_url: 'https://harris-gomez.com/',
      },
      {
        type: 1,
        company_name: 'Reed, Johnson and Bowers',
        company_email: 'gadams@example.net',
        company_phone_number: 193194570971,
        tax_code: '6488726501',
        size: 1,
        company_location: '65251 Santos Loaf, New Thomas, Idaho 89001, Cameroon',
        company_description: 'Face-to-face composite archive',
        company_website_url: 'https://miller.biz/',
      },
      {
        type: 1,
        company_name: 'Little PLC',
        company_email: 'freemancharles@example.com',
        company_phone_number: 492193635443,
        tax_code: '0354739439',
        size: 5,
        company_location: '4449 Vincent Row, Johnfurt, Delaware 32957, Croatia',
        company_description: 'Diverse attitude-oriented synergy',
        company_website_url: 'http://www.gordon-johnson.com/',
      },
      {
        type: 2,
        company_name: 'Hansen-Scott',
        company_email: 'laura04@example.com',
        company_phone_number: 410839160271,
        tax_code: '7095332132',
        size: 4,
        company_location: '67989 Jessica Estates, Thomasville, Virginia 71854, Iceland',
        company_description: 'Stand-alone dedicated system engine',
        company_website_url: 'https://hill.com/',
      },
      {
        type: 1,
        company_name: 'Neal-Diaz',
        company_email: 'bellkatherine@example.com',
        company_phone_number: 31497569743,
        tax_code: '7779967878',
        size: 3,
        company_location: '2464 Murillo Plains, Martinstad, Maryland 27888, Morocco',
        company_description: 'Diverse dynamic artificial intelligence',
        company_website_url: 'http://www.hernandez.org/',
      },
      {
        type: 1,
        company_name: 'Doyle, Moon and Duran',
        company_email: 'cruzkaren@example.org',
        company_phone_number: 327402386255,
        tax_code: '6413671152',
        size: 2,
        company_location: '4431 Katherine Square, South Christine, North Carolina 03077, Cameroon',
        company_description: 'Progressive 24hour Graphical User Interface',
        company_website_url: 'https://www.cruz.org/',
      },
      {
        type: 1,
        company_name: 'Hughes-Wood',
        company_email: 'christopher43@example.net',
        company_phone_number: 455550228926,
        tax_code: '7730457136',
        size: 5,
        company_location:
          '20406 Phillip Village, Richardsonhaven, Iowa 84742, Saint Pierre and Miquelon',
        company_description: 'Customer-focused context-sensitive access',
        company_website_url: 'https://www.shah.info/',
      },
      {
        type: 2,
        company_name: 'Ward, Myers and Hale',
        company_email: 'grobertson@example.com',
        company_phone_number: 865651103873,
        tax_code: '1590101317',
        size: 1,
        company_location: '018 Gina Walk, Jasonmouth, Maryland 51602, Syrian Arab Republic',
        company_description: 'Customizable directional leverage',
        company_website_url: 'https://www.brown.com/',
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete('company', null, {});
  },
};
